title: "Xiaoxi (Amanda) Liu"
description: "Studies on credit market, banks, and international finance"
theme: jekyll-theme-cayman

markdown: kramdown

header_pages:
  - publications.md
  - notes.md
  - visual-lab.md
