title: "Xiaoxi (Amanda) Liu"
description: "Studies on credit market, banks, and international finance"
theme: minima

markdown: kramdown

header_pages:
  - projects.md
  - publications.md
  - notes.md
  - visual-lab.md
